# Generated by Django 5.0.9 on 2026-09-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title_hi', models.CharField(max_length=250)),
                ('title_en', models.CharField(max_length=250)),
                ('desc_hi', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('location_hi', models.CharField(max_length=250)),
                ('location_en', models.CharField(max_length=250)),
                ('organizer_hi', models.CharField(max_length=250)),
                ('organizer_en', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='events/%Y/%m/')),
                ('registration_url', models.URLField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='departments.department')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
