# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc_en',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc_hi',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
    ]
