# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('question_hi', models.CharField(max_length=300)),
                ('question_en', models.CharField(max_length=300)),
                ('answer_hi', models.TextField()),
                ('answer_en', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
