# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
    ]
