# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('name_hi', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250)),
                ('desc_hi', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True)),
                ('file', models.FileField(help_text='PDF or document to download.', upload_to='resources/%Y/%m/')),
                ('icon', models.CharField(default='FileDown', max_length=50)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
