# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(help_text='PDF to download.', upload_to='resources/%Y/%m/', validators=[apps.core.validators.PDFFileValidator()]),
        ),
    ]
