# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_hi', models.TextField()),
                ('intro_en', models.TextField()),
            ],
            options={
                'verbose_name': 'About page content',
                'verbose_name_plural': 'About page content',
            },
        ),
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('title_hi', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('desc_hi', models.TextField()),
                ('desc_en', models.TextField()),
                ('icon', models.CharField(default='Target', help_text='Lucide icon name: Target, Users, BookOpen, etc.', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
