# Generated by Django 5.0.9 on 2026-09-07 11:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='intro_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='intro_hi',
            field=tinymce.models.HTMLField(),
        ),
    ]
