# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('name_hi', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description_hi', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(default='Wheat', help_text='Lucide icon name used by the frontend, e.g. Wheat, Building2, TreePine, PawPrint.', max_length=50)),
                ('color_tone', models.CharField(default='bg-green-100 text-green-700', help_text='Tailwind classes for the icon badge tone.', max_length=50)),
            ],
            options={
                'ordering': ['order', 'name_en'],
            },
        ),
    ]
