# Generated by Django 5.0.9 on 2026-09-07 11:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL path, e.g. 'privacy-policy' or 'terms-conditions'.", max_length=100, unique=True)),
                ('title_hi', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('content_hi', tinymce.models.HTMLField()),
                ('content_en', tinymce.models.HTMLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
