# Generated by Django 5.0.9 on 2026-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration_days',
            field=models.PositiveSmallIntegerField(choices=[(7, '7 days'), (15, '15 days'), (30, '30 days')], default=7, help_text='Requested run length, in days — chosen by the advertiser when submitting.'),
        ),
    ]
