# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='ads/pdf/%Y/%m/', validators=[apps.core.validators.PDFFileValidator()]),
        ),
    ]
