# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
    ]
