# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPaperIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('title_hi', models.CharField(default='कृषि मंथन ई-पेपर', max_length=200)),
                ('title_en', models.CharField(default='Krishi Manthan E-paper', max_length=200)),
                ('issue_date', models.DateField(unique=True)),
                ('pdf_file', models.FileField(upload_to='epaper/pdf/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='epaper/thumb/%Y/%m/')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
