# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaperissue',
            name='pdf_file',
            field=models.FileField(upload_to='epaper/pdf/%Y/%m/', validators=[apps.core.validators.PDFFileValidator()]),
        ),
        migrations.AlterField(
            model_name='epaperissue',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='epaper/thumb/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
    ]
