# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_hi', models.CharField(max_length=100)),
                ('city_name_en', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_default', models.BooleanField(default=False)),
                ('manual_temp_c', models.DecimalField(decimal_places=1, default=28.0, max_digits=4)),
                ('manual_condition_hi', models.CharField(default='साफ आसमान', max_length=100)),
                ('manual_condition_en', models.CharField(default='Clear Sky', max_length=100)),
                ('manual_humidity', models.PositiveIntegerField(default=45)),
                ('manual_wind_kmh', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
            ],
        ),
    ]
