# Generated by Django 5.0.9 on 2026-09-07 11:49

from django.db import migrations, models


def fix_duplicate_defaults(apps, schema_editor):
    """If more than one WeatherCity was marked default (a state the old
    model allowed), keep only the most recently added one as default so
    the sidebar widget has an unambiguous city to show."""
    WeatherCity = apps.get_model("weather", "WeatherCity")
    defaults = list(WeatherCity.objects.filter(is_default=True).order_by("-id"))
    if len(defaults) > 1:
        keep = defaults[0]
        WeatherCity.objects.filter(is_default=True).exclude(pk=keep.pk).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercity',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Only one city can be default — marking this one automatically un-marks any other.'),
        ),
        migrations.RunPython(fix_duplicate_defaults, migrations.RunPython.noop),
    ]
