# Generated by Django 5.0.9 on 2026-09-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('name_hi', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250)),
                ('overview_hi', models.TextField()),
                ('overview_en', models.TextField()),
                ('benefits_hi', models.TextField()),
                ('benefits_en', models.TextField()),
                ('eligibility_hi', models.TextField()),
                ('eligibility_en', models.TextField()),
                ('process_hi', models.TextField()),
                ('process_en', models.TextField()),
                ('image', models.ImageField(upload_to='schemes/%Y/%m/')),
                ('apply_url', models.URLField(blank=True, help_text='Official application link, if available.')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='departments.department')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
