# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='benefits_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='benefits_hi',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility_hi',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='image',
            field=models.ImageField(upload_to='schemes/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='process_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='process_hi',
            field=tinymce.models.HTMLField(),
        ),
    ]
