# Generated by Django 5.0.9 on 2026-09-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_hi', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'News categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title_hi', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('summary_hi', models.TextField()),
                ('summary_en', models.TextField()),
                ('content_hi', models.TextField(blank=True, help_text='Full article body (Hindi).')),
                ('content_en', models.TextField(blank=True, help_text='Full article body (English).')),
                ('image', models.ImageField(upload_to='news/%Y/%m/')),
                ('author', models.CharField(default='Krishi Manthan Desk', max_length=150)),
                ('published_date', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='news.newscategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='departments.department')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
