# Generated by Django 5.0.9 on 2026-09-07 11:55

import apps.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Full article body (English).'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content_hi',
            field=tinymce.models.HTMLField(blank=True, help_text='Full article body (Hindi).'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(upload_to='news/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()]),
        ),
    ]
