# Generated by Django 5.0.9 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public API without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('crop_name_hi', models.CharField(max_length=100)),
                ('crop_name_en', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_hi', models.CharField(default='क्विंटल', max_length=50)),
                ('unit_en', models.CharField(default='qtl', max_length=50)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('flat', 'Flat')], default='flat', max_length=10)),
            ],
            options={
                'ordering': ['order', 'crop_name_en'],
            },
        ),
    ]
